name: Trigger auto deployment
on:
  # 手動実行用トリガー
  workflow_dispatch:
   
# Add envs 
env:
  RESOURCE_GROUP_NAME: Handson01-CICD
  CONTAINERAPP_NAME: ctapp-demo-ui
  API_BASE_URL: https://ctapp-demo-api.ambitioussea-087c7fc4.koreacentral.azurecontainerapps.io
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set repository name to env
        run: | 
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

      - name: Confirm if env have REPOSITORY_NAME
        run: |
          echo ${{ env.REPOSITORY_NAME }}

      # Add a step
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az extension add --upgrade --name containerapp

            az containerapp registry set \
              --name ${{ env.CONTAINERAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --server ${{ env.CONTAINER_REGISTRY }} \
              --username  ${{ secrets.CONTAINER_REGISTRY_USERNAME }} \
              --password ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

            az containerapp ingress enable \
              --name ${{ env.CONTAINERAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --target-port 3000 \
              --type external

            container_name=$( \
              az containerapp show \
                --name ${{ env.CONTAINERAPP_NAME }} \
                --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
                --query "properties.template.containers[0].name" \
                --output tsv
            )
            az containerapp update \
              --name ${{ env.CONTAINERAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --container-name $container_name \
              --image ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }} \
              --set-env-vars API_BASE_URL=${{ env.API_BASE_URL }}
